### ISSUE TITLE
Pages in Text file

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#138]
Just to make sure:
The data dictionary says for the text file that the "pages" column contains "Page number in text that the column source_id refers to". The text file for me is a rather bibliographical file, it often does not make sense to include any source id, which refers to itself. I figure that we have sometimes even jotted down the general number of pages of the book. 
Thinking it through we'll get to the point at which it might be consequential to fully delete the columns "Source_id" and "pages".

So how do we at best deal with it?

**Comment by duncdrum** [comment]
It depends on how consistently the data input was. If [L45](https://github.com/LenaHenningsen/ReadingData/blob/master/data/helper/data_dictionary.csv#L45) is accurate then all instances of source_id would end up in the acts table, and there would no longer be a need to records them in the text table. 
In my mind source_id only makes sense as part of text.csv if we sometimes record that a text exists, via an indirect quote. e.g.:
```
Mr. X remembers reading the yellow edition of Mao's collected quotations...
```
would go with Text.csv:

id|title|source|note
---|---|---|---|
T01|Mr. X Diary | | a very nice diary
T02|Little Yellow Book | T01| a lost yellow version of the little red book

**Comment by inamoto4** [comment]
Mira and I got to the following conclusion:
The text file is a pure bibliographical file that records texts, no acts! 
The above-mentioned T01 and T02 approach is not correct! The source_id for a text is only relevant in cases of poems, articles, online pieces (not: novels, monographies). The source_id only records where a text was published, everything else goes into the act table. 

I have already changed the data_dict, which will take effect with my new PR.

PS: The grunt work is done for the person table, and with this proposal for the text table, too. However, I have the feeling that we still need to think a bit more about the act_type file and the act file. But we are definitely on a good way!

**Comment by duncdrum** [comment]
@inamoto4 sounds good to me. Agreed on ActTypes needing work, I want Lena to give some more feedback on this first though. 
Since you have a better overview of the documents, can you fix what is already in the csvs first, though? Namely the `editionness` of `text.csv`, the contents of its `source_id` and the secondary_sources table that is now necessary.

**Comment by inamoto4** [comment]
Is a secondary sources table really necessary? How about Jintian, the journal edited from 1978/9 onward by former Zhiqing? Is this a primary or a secondary source? How about 回忆录? It is pretty tough to separate those, that is why I am still not 100% sure whether to split the text table into two would be a good idea.

The editionness and source_id will be tackled by me and Mira in the next step, i.e. next week. After that we will work on the act_type table and the act table. I think by then the grunt work is completed.

**Comment by duncdrum** [comment]
Since it makes little sense to have Nature articles from 2000 recorded as first PRC edition, I'd say yes we need a secondary sources table. 

I thought that the question of primary or secondary source depends on the reading acts it is associated with, no? If somebody talks about reading *Jintian* it is primary, if we people report reading *Faust* in an article in *Jintian* it is secondary. In cases where we have both for the same source, `text.csv` takes precedence, time-travel not being a thing and all …

**Comment by inamoto4** [comment]
We have publication date and first Chinese edition, no first PRC edition. The first PRC edition is a subcategory for publication date and is only relevant for texts published in China. It is a Behelfskonstrukt, which enables us to get close to editions, which might have been used at that time. 

I do not see in how far this contributes to the question of whether to split up the table or not.
