### ISSUE TITLE
Inclusion of friends

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#170]
It is probably a hard thing to formalise friendship. My tentative suggestion would be the following:

Let us set up a table similar to the family one, yet added by one column:  degree of friendship
a) close friendship b) acquaintance 

Through the entry of the friend we are able to say whether they went to the same 下乡地点 or are from the same place. Unfortunately, not a few of them were born around 1950 and went to Beijing a little later, so that they in fact grew up in the capital, yet we have no record of that in our database. But I understand that you can never include everything.

We are also interested if sbd was member of group or literary society. How about if we include this into the person file? Another column called "group affiliation" should be added. 
We would fill in the name of the literary society or group in the institution table and add I00xx... in the column "group affiliation" in the person file.

Both aspects are hard to qualify, but it would greatly help us to understand and visualize social and intellectual dynamics of that time.

**Comment by duncdrum** [comment]
If we only have one relations in addition to kinship, I would suggest using the kinship table, renaming it to `SocialRelation.` Per convention in SNA, friendships are loosely defined. 
I would record the degree using numbers `1` = loosely acquainted, `2` = friendship, `3` = close friend (you might consider `0` = dislike if we have such cases). Obviously, these definitions should go into the data-dictionary.     
The main question with groups is if you want to trace membership over time. So that PXXXX was part of a literary circle (I01) between 1974-1978, but a Party Member (I02) from 1955-1997, persons have the tendency to be members of multiple institutions.
We initially expected to track membership in `Institution.members_id`. If all we are dealing with are simple cases (no dates) I would stick with that to not clutter `Person`. If we want to track the life-span of institutions (the literary circle is only around as long as the persons in our DB are part of it, but the party continues) then a separate table to track the relationship between `Person` and `Institution` is the way to go.

**Comment by inamoto4** [comment]
Telling from my experience with the texts, it would be hard to distinguish three levels of "knowing each other", as even long friendships are often only mentioned en passant. Names are given and then one has to infer whether this describes a friendship or an acquaintance. Therefore, in my understanding establishing two levels would already pose a challenge, but could be justified by the better grasp of reality we have after doing that. 

In the same way we can draw a timeline for literary circles, we could do so with friendships. But this would of course be too much. So, record as simple as possible while display as complex as necessary might be a usual database motto.

In case of literary circles, it might actually be very useful to have this information, but to keep it simple I would again not go for another table. A good idea might be the addition of another column into the institution table. 
Those literary circles have had only a short life span, so they are quite different from big organizations like the CP. An overall timeframe for the whole institution could therefore suffice in our case.

**Comment by duncdrum** [comment]
I'm fine with how every many levels you think are in the data, as long as they are encoded using numbers. 

Another table is actually simpler then integrating the life-span information into `Person` and `Institution`, since we need to separate the start and end dates of the group as a separate entity (that could go into `Institution`) from the participation period for individual members. Think Ringo's gig with the Beatles. 

We would add considerable complexity to `Person` if we have to add multiple membership dates to some person records and zero to others. A separate table is much cleaner, since it won't lead to empty cells, and limit the number of columns in `Person`

**Comment by inamoto4** [comment]
My idea would be to not add any membership dates into the person table. Just say he was member of I004, end of story. For that we could allow for two or three exta columns in the person file, as one person can of course be member of several literary groups or societies. In the institution table we would put one extra column for the dates of its existence, for example in the case of the baiyangdian literary society it would be around 1969-1976. To track these dates is much easier than the dates of the membership of every single member. Another additional table should be added for the locus of the society. 

We also have the information when our Zhiqing went to their 下乡地点 and when they returned to Beijing or Shanghai. Taken together with the locus of the literary society, it would allow for an even more precise time of the membership, whether the societies were in the countryside or in a big city.

**Comment by duncdrum** [comment]
Still make a `Membership` table with just Institution and person id's. Every time you think: just
> two or three exta columns

 you are off to a bad start. 
many small tables >>>> one big table

No need for another table for location, we already have one. Simply add the location id from `Place` to `Institution.place` (and add the missing locations to `Place`). It will require a sentence on how we determine the location, and how we deal with the fact that institutions move (think Bonn -> Berlin)

I'm fine with just tracking the life span of institutions, and not membership. For consistencies sake, and greater efficiency, it should happen via *two* columns (start and end) in `Institution` though.

**Comment by LenaHenningsen** [comment]
I think for these relations no time is necessary; you are son of your parents all your life (and do not escape their class background) - and friendship / comradeship (well, without party "Beigeschmack") seems astonishingly stable over time

**Comment by duncdrum** [comment]
Since we use the extended version for Chinese kinship terms, we best stick with the same thesaurus for other relationships. Looking at the [USAS](http://ucrel.lancs.ac.uk/usas/) base annotations we have:

>S3	Relationship
S3.1	Personal relationship: General
S3.1-	No personal relationship 
S3.2	Relationship: Intimacy and sex
S3.2+	Relationship: Sexual
S3.2-	Relationship: Asexual

 So 
-  `S3.1` becomes `acquaintance` and 
-  `S3.2-` becomes `friend`. 
We haven't discussed intimate relationships, but I think:
-  `S3.2+` could be a useful distinction for `friend (intimate)`, or we could simply ignore it and keep the database PG 12. 

see #182

**Comment by inamoto4** [comment]
In the list I have it says for kinship:
S4	Kin
S4-	No kin

Nothing more. But we have the very detailed list for S4 from Piao/Qian, and I guess for S3 there might be something more elaborate too? If I understand it correctly, 3.2- explicitly states that a relationship was asexual, which we actually do not know. But maybe we can just define it differently.

**Comment by duncdrum** [comment]
There is only `3.1` and `3.2` see the link. I would suggest that we assume platonic friendships unless indicated otherwise. `3.2-` being the default for close friends, unless they explicitly had a romantic relationship. 
We could add further subcategories, e.g. `3.1.1` classmate at a later point in time, but as far as the semantics of `3.1` and `3.2` we should not change their definitions.

**Comment by LenaHenningsen** [comment]
I would like to keep it as simple as possible, maybe only 3.1 and 3.2 - I find it difficult to determine where intimacy begins and where not; we might even only lis ONE marker for friendship, if we have it really broad, as we said on Skype last week...

**Comment by duncdrum** [comment]
Yes I think the majority of cases will be either `3.1` or `3.2-`, but I can see that terms like `男朋友` or stories to the tune of  `I was in love with this guy from the country side… ` do express a different kind of friendship that we should be able to model. 

here is my take on the data-dictionary entry:

SocialRelation | relation | Relation based on UCREL/USAS semantic classes. Chinese kinship according to extensions proposed by Qian & Piao (2007). By default close friends have intimate asexual relations (S3.2-). Romantic relations are assumed to be sexual (S3.2+). Absent or antipathetic relations are not recorded.|
| --- | --- | --- |
SocialRelation | rel_zh | Name of relation in Chinese. '朋友' for close friends (S3.2±). '熟人' as default unspecific relation (S3.1)|
SocialRelation | rel_en | 	Simple kinship term in English ('sister' 'grandfather' …). 'friend' (S3.2±) & 'acquaintance' (S3.1) for non-kinship relations|

**Comment by LenaHenningsen** [comment]
Ok, I agree that this makes sense.

Thanks for clarification!

Yes I think the majority of cases will be either 3.1 or 3.2-, but I can see that terms like 男朋友 or stories to the tune of I was in love with this guy from the country side… do express a different kind of friendship that we should be able to model.

here is my take on the data-dictionary entry:

SocialRelationrelationRelation based on UCREL/USAS semantic classes. Chinese kinship according to extensions proposed by Qian & Piao (2007). By default close friends have intimate asexual relations (S3.2-). Romantic relations are assumed to be sexual (S3.2+). Absent or antipathetic relations are not recorded.
SocialRelationrel_zhName of relation in Chinese. '朋友' for close friends (S3.2±). '熟人' as default unspecific relation (S3.1)
SocialRelationrel_enSimple kinship term in English ('sister' 'grandfather' …). 'friend' (S3.2±) & 'acquaintance' (S3.1) for non-kinship relations
