### ISSUE TITLE
act types (hierarchization)

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#174]
@duncdrum @inamoto4 @mira-gruenwald @BIGBUNNIEEEE +
The second issue arising with the act types concerns hierarchization. It makes a difference whether someone writes in his autobiography that he read a book (or tore it apart or whatever) - or whether a secondary source claims that a certain book at the time was popular (I say claim here because some of the sources are rather homeopathic in the amount of evidence that they provide...). Both sources, of course, come with constraints (as to the trustworthiness of their truth claims etc. However it makes a difference for the framework whether we have a distinct statement about an action by one person - or the more distant claims arising from the other type of source. (A third type of source would be fictional texts as source of information on reading habits, but this is for later in the project).
These different statuses of the sources ought to be visible. My suggestion is to add a column into the ACT File for status of the source (for which we then need another table I guess?? Or can we hijack the genre file for that??)
life writing (that would be the largest possible denomination for all sorts of autobiographical texts...)
secondary source
fictional text (this is for later, but will be necessary).
@duncdrum  does that make sense?
@inamoto4 should we add more "evaluation" by adding a qualifier like "secondary source with no / insufficient evidence"?
Thanks a lot everyone

**Comment by duncdrum** [comment]
a separate table would be necessary if we expect these categories to grow to more then say 10, and if we want to give additional information about them, e.g. names in both Chinese and english terms. 
For 2 + 1 categories using abstract values `01`, `02`, etc and defining them in the data-dictionary is sufficient. 
I m intrigued by the idea of using top level genre classifiers, but I m not sure if we have a genre that matches `secondary source`, @inamoto4 thoughts?

**Comment by LenaHenningsen** [comment]
… it may be academic writing as a more general term…

a separate table would be necessary if we expect these categories to grow to more then say 10, and if we want to give additional information about them, e.g. names in both Chinese and english terms.
For 2 + 1 categories using abstract values 01, 02, etc and defining them in the data-dictionary is sufficient.
I m intrigued by the idea of using top level genre classifiers, but I m not sure if we have a genre that matches secondary source, @inamoto4 thoughts?

**Comment by inamoto4** [comment]
Thoughts, no ready solution:
Xiao Xiao 1999 mentions about 40 books that were supposedly the most important neibu publications. We already have the qualification of the source through the Genre type, i.e. academic writing. 
If we do not take "to mention" as an act, we might have the books in our database, yet they are not really displayed in the decisive act file. We could also add a "supposedly" for unfounded sources in the important commentary cell , if we want to include it in the act table. 
In one way or another we will might highlight the differences between academic writing and life writing, which is possible with the data we are now collecting. 
I would just urge everybody to finish all structural changes within the next weeks, because if we are adding new qualifiers, we will have to go over all acts again, and this costs endless time.
