### ISSUE TITLE
some remarks

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#19]
UPDATED VERSION after Talk between Lena and Oliver (18 July):
@duncdrum 
Would be great if you could answer the following questions:
 
1) Location: 
We want to include the locations in the acts table, yet I would say that for more than 80% of the sample there will simply be no information available. Do we in this case need an own column? And would we have to add another one for Place? We have the places of rustication and the birth places through the Person_ID, yet the reading could have happened in another place. An (unlikely?) alternative could be, to use keywords in the substantial discussion like place and location whenever we are referring to those additional information?

2) Texts: How do we include everything which was not printed as a book? I am here especially referring to the secondary sources which could be Interviews in China, Internet sources etc. The columns are not fitting then.

3) Texts: If we got several important sources for an entry in the text table, they would then be written into the note field, correct?

4) Acts: We somehow still do not understand the following:
Person A (1) gives Book X (2) to Person B (3). How can this dynamic be modeled in our table? We basically only have to two columns (agent and agens).
 
5) We will get a field for specificity of time, right? I guess it would be useful for persons/time of rustication and the act table.

6) We would usually use wikipedia to get the basic information on foreign authors in the person table. Shall this always be written into the source column as en.wikipedia.org/ its respective Source_ID? See also question 2)

**Comment by duncdrum** [comment]
*   Location 
if the location is ``unknown`` but the other instances of the act have this information leave it in the table. Otherwise make an aux table for ActLocation to only record locations where they need to be. 

*   texts
have a look at [typeOfResource](http://www.loc.gov/standards/mods/mods-outline-3-6.html#typeOfResource) from the mods standard. 

*  source
Each line has one main source in the ``source`` column. Additional sources go into ``note``

*   Acts
there should be three: agent, act, agens
```
A    gives       ThingX
B    receives    ThingX
```

*   Time 
See [extended date-time format](https://www.loc.gov/standards/datetime/). Where that doesn't suffice an additional column ``precision`` will be necessary.

*   wikipedia
for wikipedia and online resources you could simply post the full uri in the source field, eg.:
``https://en.wikipedia.org/wiki/Lu_Xun``

**Comment by duncdrum** [comment]
I put the links into the wiki's [FAQ](https://github.com/LenaHenningsen/ReadingData/wiki/FAQ). I'd suggest closing this and open new issues for future questions.
