### ISSUE TITLE
Author without a title

### ISSUE THREAD

**Issue by inamoto4** [LenaHenningsen/ReadingData#196]
I think that I have already asked that question, yet I cannot find it anymore. 

If we have the sentence:
I have read Goethe during my youth over and over again; how do we record that?
Creating a text entry and put _Unknown_ in title and bibliographical details, and then adding the author? 
I think it would not be a good solution to have an act such as: "P0002 read P0001." Persons are no texts.

**Comment by duncdrum** [comment]
The answer depends on how we exactly split `Text`. So let's keep this open for now.

**Comment by duncdrum** [comment]
I'd suggest adding a fixed phrase into a newly created comments fields in Act along the lines of`unknown work by:` followed by the person-id. 
This would avoid having out sources cluttered with potentially unlimited unknown books for every author, while simultaneously not making bad assumptions that every CR period reader reading the same title when they claim to read "Goethe".  We need an extra column so we can model A gives B unknown book X by author C.

**Comment by inamoto4** [comment]
Would it be potentially unlimited or couldn't we just subsume all books by one author which do not bear a specific title with the title `unknown`?

**Comment by duncdrum** [comment]
I m afraid it ll be ∞, since subsuming would go against our entity model.

**Comment by inamoto4** [comment]
On the other hand we have one P0999, which covers all unknown people. Is that really different from the `unknown` text?

**Comment by duncdrum** [comment]
Yes,  we have **one** unknown entry (in principle for every table). However, you question in the OP is about how to record: "Mrs X read an unknown book by Goethe" we would need a specific object in the act table, so that Mrs. X doesn't read all unknown books past and future.  

Hence my suggestion to combine **one** unknown source, with additional information per act in `Act`. It's really either `1` or `∞` unknown entities in sources. In which case the preferable answer is always: `1`

**Comment by damianodamiani** [comment]
OK, so PS09999 + "unknown work by: P0xxx" it is. Thanks for linking me here!

**Comment by damianodamiani** [comment]
aha, one more thing: if that refers to artworks (e.g. "Schubert's music") should I also use PS09999 or rather AW09999?

**Comment by duncdrum** [comment]
@damianodamiani see #235
