### ISSUE TITLE
ID numbers

### ISSUE THREAD

**Issue by damianodamiani** [LenaHenningsen/ReadingData#241]
During our meeting, while assigning to each other numbers of various databases, we noticed that the overall number of character spots differs from spreadsheet to spreadsheet. And so some entries have five (e.g. Institution [I0029], Person [P0102]), others six (e.g. Place [PL0240], Act [A00234]), others have seven (e.g. PrimarySource [PS00328], SecondarySource [SS00249]), and still others have eight (e.g. ArtWork [AW000100]). 

Is that intentional? And if yes, why?

If not, should we solve this by removing the 0's from the entries with more than five character spots / adding 0's to those which have less than six characters spots? Or is there a better way?

I don't know if it really matters but it's just a bit confusing when entering the data - we always need to re-check which spreadsheet has how many 0's...

**Comment by duncdrum** [comment]
This is intentional. The length represents how many entries we conceive of having with respect to future extensions. Eight for ArtWork seems excessive five should suffice there. But i wouldn't want people wasting time on fixing this across the whole DB. 
You can just click-drag down in the ID column and the spreadsheet app should auto-fill new numbers.

**Comment by damianodamiani** [comment]
OK, understood. We leave it like is for now.
